INSERT INTO CLUB (COUNTRY_ID, NAME, URL) VALUES
('BE', 'Lokeren', '/lokeren/hxt6OGUj'),
('DE', 'Magdeburg', '/magdeburg/YFuz2RLm'),
('DE', 'Ingolstadt', '/ingolstadt/ne5QkLtB'),
('DE', 'Duisburg', '/duisburg/2s7huW4R'),
('DE', 'Kaiserslautern', '/kaiserslautern/naWckLmC'),
('DE', 'Braunschweig', '/braunschweig/QqLCC3il'),
('EN', 'Ipswich', '/ipswich/thqhB2MB'),
('EN', 'Bolton', '/bolton/Or1bBrWD'),
('EN', 'Rotherham', '/rotherham/KMfM7P4b'),
('EN', 'Burton', '/burton/nwCtJaJT'),
('EN', 'Sunderland', '/sunderland/WSzc94ws'),
('FR', 'Ajaccio GFCO', '/gfc-ajaccio/QZuxDxup'),
('FR', 'Red Star', '/red-star/2kM6ufaS'),
('FR', 'Beziers', '/beziers/CWwUNPzA'),
('FR', 'Quevilly Rouen', '/quevilly/fPCzUHN1'),
('FR', 'Tours', '/tours/lrpZ4Lr7'),
('FR', 'Bourg Peronnas', '/bourg-peronnas/Ict2iv2P'),
('GR', 'Giannina', '/giannina/rN9JmpKO'),
('GR', 'Levadeiakos', '/levadiakos/YouAGdPF'),
('GR', 'Apollon', '/apollon-larissa/fZZKVfF0'),
('GR', 'Kerkyra', '/kerkyra/EwjJpjDJ'),
('GR', 'Platanias', '/platanias-fc/xM5CMJdn'),
('IT', 'Palermo', '/palermo/n38Nktmn'),
('IT', 'Carpi', '/carpi/4Mj4hjbN'),
('IT', 'Foggia', '/foggia/4nSGWbrR'),
('IT', 'Padova', '/padova/2gUwEtrE'),
('IT', 'Pro Vercelli', '/pro-vercelli/KjGeTD9G'),
('IT', 'Avellino', '/avellino/A332L1f5'),
('IT', 'Novara', '/novara/rPRQmc5D'),
('IT', 'Ternana', '/ternana/zVUNUKkf'),
('IT', 'Bari', '/bari/xIkUr2vO'),
('IT', 'Cesena', '/cesena/xddf1qfh'),
('NL', 'NAC Breda', '/breda/nLNrHc14'),
('NL', 'Excelsior', '/excelsior/nNlLsRUr'),
('NL', 'Graafschap', '/de-graafschap/naL1J006'),
('NL', 'Roda', '/roda/6FRTNZ8p'),
('PO', 'Nacional', '/nacional/4ETLrR7n'),
('PO', 'Chaves', '/chaves/vsToxqA5'),
('PO', 'Feirense', '/feirense/t4p0iC41'),
('PO', 'Estoril', '/estoril/htoKuYZl'),
('ES', 'Cordoba', '/cordoba/CWuejruc'),
('ES', 'Gimnastic', '/gimnastic/WSv960Hk'),
('ES', 'Reus Deportiu', '/reus-deportiu/IDGLjl6p'),
('ES', 'Rayo Majadahonda', '/rayo-majadahonda/8C8Kvfu4'),
('ES', 'Barcelona B', '/barcelona/K4P35GyD'),
('ES', 'Sevilla B', '/sevilla/dY03Jvn2'),
('ES', 'Leonesa', '/leonesa/O6FowKBc'),
('ES', 'Lorca', '/lorca-fc/GGDGlOLU'),
('TU', 'Bursaspor', '/bursaspor/f9yyDvc8'),
('TU', 'Akhisar Belediyespor', '/akhisarspor/lGeR4G7n'),
('TU', 'Erzurum BB', '/erzurum-bb/xQZ3CpVE'),
('TU', 'Karabukspor', '/kardemir-karabuk/UqDDmAhh'),
('TU', 'Osmanlispor', '/osmanlispor-fk/tx2Yly51');