--CREATE TABLE scheduled_item (
--	scheduled_item_id INT NOT NULL AUTO_INCREMENT,
--	spring_bean VARCHAR(30) NOT NULL,
--	retry_counter INT NOT NULL,
--	status TINYINT(1) NOT NULL,
--	created_date TIMESTAMP NOT NULL,
--	updated_date TIMESTAMP,
--	PRIMARY KEY (scheduled_item_id))
--ENGINE=InnoDB;

--CREATE TABLE scheduled_item_param (
--	scheduled_item_param_id INT NOT NULL AUTO_INCREMENT,
--	scheduled_item_id INT NOT NULL,
--	name VARCHAR(30) NOT NULL,
--	value VARCHAR(30) NOT NULL,
--	created_date TIMESTAMP NOT NULL,
--	PRIMARY KEY (scheduled_item_param_id),
--	FOREIGN KEY (scheduled_item_id) REFERENCES scheduled_item(scheduled_item_id))
--ENGINE=InnoDB;

INSERT INTO fsc_league (league_id, name, url, is_disabled) VALUES
  ('ARG1', 'ARG Superliga', '/argentina/superliga', 0),
  ('AUT1', 'AUT Bundesliga', '/austria/tipico-bundesliga', 0),
  ('AUT2', 'AUT 2 Liga', '/austria/2-liga', 0),
  ('BEG1', 'BEG Jupiler League', '/belgium/jupiler-league', 0),
  ('BEG2', 'BEG Proximus League', '/belgium/proximus-league', 0),
  ('BEL1', 'BEL Vysshaya Liga', '/belarus/vysshaya-liga', 0),
  ('BRA1', 'BRA Serie A', '/brazil/serie-a', 0),
  ('BRA2', 'BRA Serie B', '/brazil/serie-b', 0),
  ('BUL1', 'BUL Parva Liga', '/bulgaria/parva-liga', 0),
  ('CZE1', 'CZE 1 Liga', '/czech-republic/1-liga', 0),
  ('CZE2', 'CZE Division 2', '/czech-republic/division-2', 0),
  ('CHL1', 'CHL Primera Division', '/chile/primera-division', 0),
  ('DEN1', 'DEN Superliga', '/denmark/superliga', 0),
  ('DEN2', 'DEN Division 1', '/denmark/1st-division', 0),
  ('ENG1', 'ENG Premier League', '/england/premier-league', 0),
  ('ENG2', 'ENG Championship', '/england/championship', 0),
  ('ENG3', 'ENG League One', '/england/league-one', 0),
  ('ENG4', 'ENG League Two', '/england/league-two', 0),
  ('FIN1', 'FIN Veikkausliiga', '/finland/veikkausliiga', 0),
  ('FIN2', 'FIN Ykkonen', '/finland/ykkonen', 0),
  ('FRA1', 'FRA Ligue 1', '/france/ligue-1', 0),
  ('FRA2', 'FRA Ligue 2', '/france/ligue-2', 0),
  ('GRE1', 'GRE Super League', '/greece/super-league', 0),
  ('NDL1', 'NDL Eredivisie', '/netherlands/eredivisie', 0),
  ('NDL2', 'NDL Eerstedivisie', '/netherlands/eerste-divisie', 0),
  ('CRO1', 'CRO HNL', '/croatia/1-hnl', 0),
  ('ITA1', 'ITA Serie A', '/italy/serie-a', 0),
  ('ITA2', 'ITA Serie B', '/italy/serie-b', 0),
  ('ITA3A', 'ITA Serie C-A', '/italy/serie-c-group-a', 0),
  ('ITA3B', 'ITA Serie C-B', '/italy/serie-c-group-b', 0),
  ('ITA3C', 'ITA Serie C-C', '/italy/serie-c-group-c', 0),
  ('JPN1', 'JPN J-League', '/japan/j-league', 0),
  ('JPN2', 'JPN J-League Div2', '/japan/j-league-division-2', 0),
  ('KOR1', 'KOR K-League', '/south-korea/k-league-1', 0),
  ('CHI1', 'CHI Super League', '/china/super-league', 0),
  ('MEX1', 'MEX Primera Division', '/mexico/primera-division', 0),
  ('GER1', 'GER Bundesliga', '/germany/bundesliga', 0),
  ('GER2', 'GER Bundesliga 2', '/germany/2-bundesliga', 0),
  ('GER3', 'GER 3 Liga', '/germany/3-liga', 0),
  ('NOR1', 'NOR Eliteserien', '/norway/eliteserien', 0),
  ('NOR2', 'NOR Obos Ligaen', '/norway/obos-ligaen', 0),
  ('PAR1', 'PAR Primera Division', '/paraguay/primera-division', 0),
  ('PER1', 'PER Primera Division', '/peru/primera-division', 0),
  ('POL1', 'POL Ekstraklasa', '/poland/ekstraklasa', 0),
  ('POL2', 'POL Division 1', '/poland/division-1', 0),
  ('POR1', 'POR Primeira Liga', '/portugal/primeira-liga', 0),
  ('POR2', 'POR Segunda Liga', '/portugal/segunda-liga', 0),
  ('IRE1', 'IRE Premier Division', '/ireland/premier-division', 0),
  ('IRE2', 'IRE Division 1', '/ireland/division-1', 0),
  ('ROM1', 'ROM Liga 1', '/romania/liga-1', 0),
  ('RUS1', 'RUS Premier League', '/russia/premier-league', 0),
  ('RUS2', 'RUS FN League', '/russia/fnl', 0),
  ('NIR1', 'NIR Premiership', '/northern-ireland/nifl-premiership', 0),
  ('SLK1', 'SLK Fortuna Liga', '/slovakia/fortuna-liga', 0),
  ('SLO1', 'SLO Prva Liga', '/slovenia/prva-liga', 0),
  ('SCO1', 'SCO Premiership', '/scotland/premiership', 0),
  ('SCO2', 'SCO Championship', '/scotland/championship', 0),
  ('SCO3', 'SCO League 1', '/scotland/league-one', 0),
  ('SCO4', 'SCO League 2', '/scotland/league-two', 0),
  ('SPA1', 'SPA LaLiga', '/spain/laliga', 0),
  ('SPA2', 'SPA LaLiga 2', '/spain/laliga2', 0),
  ('SWI1', 'SWI Super League', '/switzerland/super-league', 0),
  ('SWI2', 'SWI Challenge League', '/switzerland/challenge-league', 0),
  ('SWE1', 'SWE Allsvenskan', '/sweden/allsvenskan', 0),
  ('SWE2', 'SWE Superettan', '/sweden/superettan', 0),
  ('TUR1', 'TUR Super Lig', '/turkey/super-lig', 0),
  ('TUR2', 'TUR 1 Lig', '/turkey/1-lig', 0),
  ('UKR1', 'UKR Premier League', '/ukraine/premier-league', 0),
  ('URU1', 'URU Primera Division', '/uruguay/primera-division', 0),
  ('WAL1', 'WAL Premier League', '/wales/premier-league', 0);

UPDATE fsc_league SET is_disabled = 1
WHERE league_id IN ('CHI1', 'IRE2', 'ITA2',
                    'ITA3A', 'JPN1', 'JPN2',
                    'KOR1', 'DEN2', 'NIR2');


INSERT INTO scheduled_item (scheduled_item_id, spring_bean, retry_counter, status, created_date, updated_date)
VALUES (1, 'step1', 0, 0, NOW(), NULL);
